### ISSUE TITLE
My Android phone not ask for camera permission, How can solve problem ?

### ISSUE THREAD

**Issue by songwutk** [patrickmonteiro/quasar-barcode-reader#7]
Test in pc webcam, my browser ask for webcam permission, so success to scan.
Test in my android phone, no camera screen, no ask for permission.

**Comment by patrickmonteiro** [comment]
@songwutk To use in cordova, it is preferable to use a cordova plugin.
For example: https://www.npmjs.com/package/cordova-plugin-barcodescanner

**Comment by songwutk** [comment]
Thanks for your answer, I run by WebApplication and found this library work https://www.npmjs.com/package/vue-qrcode-reader

**Comment by patrickmonteiro** [comment]
@songwutk If you just want to read QRcode, you can also use this other repository: https://github.com/patrickmonteiro/quasar-qrcode-reader
